version: 1.6.0.{build}
image: Visual Studio 2022

configuration:
- Release

platform:
- x64
- ARM64
- Win32

cache:
  - vcpkg_installed -> vcpkg.json
  - '%LOCALAPPDATA%\vcpkg\archives -> vcpkg.json'

matrix:
  fast_finish: true

for:
-
  branches:
    only:
      - /version-.*/

  skip_non_tags: true

-
  matrix:
    only:
      - platform: x64

  environment:
    arch: x64

-
  matrix:
    only:
      - platform: ARM64

  environment:
    arch: arm64

-
  matrix:
    only:
      - platform: Win32

  environment:
    arch: x86

init:
- pwsh: >-
    if ($env:APPVEYOR_PULL_REQUEST_HEAD_REPO_BRANCH -match '^l10n_') {
      Write-Host 'Skipping translation branch pull request'
      Exit-AppveyorBuild
    }

install:
- cmd: >-
    git submodule init

    git submodule update

    .\StarryFiles++\ThirdParty\vcpkg\bootstrap-vcpkg.bat

before_build:
- pwsh: >-
    if (Test-Path env:APPVEYOR_REPO_TAG_NAME) {
      if ($env:APPVEYOR_REPO_TAG_NAME -match '-beta(-\d)?$') {
        $env:RELEASE_MODE = 'beta'
      } else {
        $env:RELEASE_MODE = 'stable'
      }
    }

build:
  project: StarryFiles++\StarryFiles++.sln
  verbosity: minimal

after_build:
- pwsh: .appveyor\after_build.ps1

test_script:
- pwsh: .appveyor\test_script.ps1

artifacts:
- path: starryfilespp_x64.zip
- path: starryfilespp_x64_symbols.zip
- path: starryfilespp_arm64.zip
- path: starryfilespp_arm64_symbols.zip
- path: starryfilespp_x86.zip
- path: starryfilespp_x86_symbols.zip
- path: starryfilespp_x64_setup.msi
- path: starryfilespp_x86_setup.msi
- path: starryfilespp_translations.zip

before_deploy:
- pwsh: >-
    $versionComponents = $env:APPVEYOR_BUILD_VERSION -split '\.'

    $versionComponents = $versionComponents[0, 1, 2]

    $releaseBuildVersion = $versionComponents -join '.'

    if ($env:APPVEYOR_REPO_TAG_NAME -match '-beta(-\d)?$') {
      $env:RELEASE_TITLE = "StarryFiles++ $releaseBuildVersion beta"
      $env:PRERELEASE = $true
    } else {
      $env:RELEASE_TITLE = "StarryFiles++ $releaseBuildVersion"
      $env:PRERELEASE = $false
    }