files:
  - source: /StarryFiles++/StarryFiles++/StarryFiles++.rc
    translation: /Translations/StarryFiles++%two_letters_code%/StarryFiles++.rc
    languages_mapping:
      two_letters_code:
        ca: CA
        cs: CS
        da: DA
        de: DE
        es-ES: ES
        fa: FA
        fr: FR
        hu: HU
        it: IT
        ja: JA
        ko: KO
        nl: NL
        'no': 'NO'
        pl: PL
        pt-PT: PT
        ro: RO
        ru: RU
        si-LK: SI
        sv-SE: SV
        tr: TR
        uk: UK
        vi: VI
        zh-CN: ZH
